#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)] // Optional, but cleans up warnings for unused C functions

// Include the bindings generated by bindgen in the build script
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
