use anyhow::Result;
use codegen::{Gen, Generator};
use ree_lib::il2cpp::{self, Il2Cpp};
use clap::Parser;


#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
pub struct Args {
    #[arg(
        short,
        long,
        default_value = "il2cpp_dump.json",
        help = "path to il2cpp dump generated by reframework"
    )]
    il2cpp: String,
    #[arg(
        short,
        long,
        default_value = "output",
        help = "path to generate files to"
    )]
    target_path: String,
    #[arg(
        short,
        long,
        help = "list of types to generate for"
    )]
    types: Vec<String>,
}

pub fn load_il2cpp<'a>(data: &'a [u8]) -> Result<Il2Cpp<'a>> {
    let mut deserializer = sonic_rs::Deserializer::from_slice(data);
    let il2cpp = il2cpp::deserialize_il2cpp(&mut deserializer)?;
    Ok(il2cpp)
}

fn main() -> Result<()>{
    env_logger::Builder::from_env(
        env_logger::Env::default().default_filter_or("info")
    ).init();

    let args = Args::parse();
    let data = std::fs::read(args.il2cpp)?;
    let il2cpp = load_il2cpp(&data)?;
    
    let generator = Generator::new(args.types, &args.target_path, &il2cpp);
    generator.generate();

    //let ty = il2cpp.get("snow.enemy.EnemyMarionetteComboCommandInfo").unwrap();
    //let (tokens, deps) = ty.generate(&il2cpp);
    //println!("deps={deps:?}");
    //println!("{}", tokens);
    Ok(())
}
